name: Docker Image CI

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
    paths-ignore:
      - 'examples/**'
      - 'docs/**'
      - '**/*.md'
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ''
  # github.repository as <account>/<repo>
  IMAGE_NAME: wecoding/iam-frontend

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Print commit ID
      run: echo "The commit ID is ${{ github.sha }}"

    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc
      uses: docker/login-action@v2.2.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ${{ env.REGISTRY }}
        # Username used to log against the Docker registry
        username: ${{ secrets.DOCKER_USER }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.DOCKER_PWD }}

    - name: Extract Docker Metadata
      # You may pin to the exact commit or the version.
      # uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175
      uses: docker/metadata-action@v4.6.0
      id: meta
      with:
        # List of Docker images to use as base name for tags
        images: ${{ env.IMAGE_NAME }}
        # List of tags as key-value pair attributes
        tags: |
          # set latest tag for default branch
          type=raw,value=latest,enable={{is_default_branch}}
          # tag event
          type=ref,enable=true,priority=600,prefix=,suffix=,event=tag

    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825
      id: docker_build
      uses: docker/build-push-action@v4.1.1
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}
